name: Python Package using Conda

on:
  push:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
#     - name: Add conda to system path
#       run: |
#         # $CONDA is an environment variable pointing to the root of the miniconda directory
#         echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install requests pendulum
    - name: Run Python
      run: |
        cd dorm_elec
        python dorm_elec.py
    - name: Commit changes
      run: |
        git config --global user.email BOT@github.com
        git config --global user.name githubBOT
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GTOKEN}}
